agroligon/models/__init__.py
from agroligon.models import user, oauth, region, municipality, product

agroligon/models/municipality.py
from agroligon import db
from agroligon.models.region import Region


class Municipality(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String())
    region_id = db.Column(db.Integer, db.ForeignKey(Region.id), nullable=False)
    region = db.relationship(Region, backref='municipalities')

agroligon/models/oauth.py
from flask_dance.consumer.storage.sqla import OAuthConsumerMixin

from agroligon import db
from agroligon.models.user import User


class OAuth(db.Model, OAuthConsumerMixin):
    __tablename__ = 'oauth'

    # The Facebook user ID
    provider_user_id = db.Column(db.String(256), unique=True, nullable=False)

    # The Agroligon user ID
    user_id = db.Column(db.Integer, db.ForeignKey(User.id), nullable=False)

    # The User model association
    user = db.relationship(User)

agroligon/models/product.py
from agroligon import db
from agroligon.models.user import User


class Product(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    producer_id = db.Column(db.Integer, db.ForeignKey(User.id), nullable=False)
    quantity = db.Column(db.Integer())
    created_at = db.Column(db.DateTime(), default=db.func.now())

    producer = db.relationship(User, backref='products')

agroligon/models/region.py
from agroligon import db


class Region(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String())

agroligon/models/user.py
from flask_login import UserMixin

from agroligon import db


class User(UserMixin, db.Model):
    __tablename__ = 'users'

    # Unique user ID
    id = db.Column(db.Integer, primary_key=True)

    # Details from Facebook
    name = db.Column(db.String(256), unique=True)
    email = db.Column(db.String(254), unique=True)
    picture = db.Column(db.Text())

    phone = db.Column(db.Integer())
    role = db.Column(db.Enum('customer', 'producer'))
    points = db.Column(db.Integer())
    created_at = db.Column(db.DateTime(), default=db.func.now())

agroligon/__init__.py
import os

from flask import Flask
from flask_login import LoginManager
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()


def create_app():
    # Create Flask application
    app = Flask(__name__, instance_relative_config=True)

    # Load configuration file from instance/ folder
    app.config.from_pyfile('config.py')

    # We enable insecure transport for OAuth so we can
    # connect with Facebook without errors about HTTPS on localhost
    if app.debug:
        os.environ['OAUTHLIB_INSECURE_TRANSPORT'] = '1'

    # Setup database SQLite3 file location
    db_prefix = 'sqlite:///'
    db_suffix = app.config['DB_FILE_NAME']
    db_file_loc = f'{db_prefix}{app.instance_path}/{db_suffix}'

    # Initialize SQLAlchemy ORM
    app.config['SQLALCHEMY_DATABASE_URI'] = db_file_loc
    db.init_app(app)

    # Initialize all models
    from agroligon import models

    # Register custom commands
    from agroligon import commands
    commands.init_commands(app)

    # Initialize login manager
    login_manager = LoginManager()
    login_manager.init_app(app)

    from agroligon.models.user import User

    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(int(user_id))

    # Register all app routes
    from agroligon import routes
    routes.init_routes(app)

    return app

agroligon/commands/__init__.py
from agroligon.commands.create_db import create_db
from agroligon.commands.drop_db import drop_db


def init_commands(app):
    # Register 'flask create-db' command
    app.cli.add_command(create_db)

    # Register 'flask drop-db' command
    app.cli.add_command(drop_db)

agroligon/routes/__init__.py
from agroligon.routes import home, login_fb, auth


# Initializes all blueprints

def init_routes(app):
    # Register '/' handler
    app.register_blueprint(home.blueprint)

    # Register '/login/facebook'
    app.register_blueprint(login_fb.blueprint, url_prefix='/login')

    # Register '/logout'
    app.register_blueprint(auth.blueprint)

agroligon/routes/auth.py
from flask import Blueprint, redirect, url_for
from flask_login import logout_user

blueprint = Blueprint('auth', __name__)


@blueprint.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('home.index'))

agroligon/routes/home.py
from flask import Blueprint, render_template
from flask_login import login_required

blueprint = Blueprint('home', __name__)


@blueprint.route('/')
def index():
    return render_template('index.html')


@blueprint.route('/search')
def search():
    return render_template('search.html')


@blueprint.route('/producer')
@login_required
def producer():
    return render_template('producer.html')


@blueprint.route('/consumer')
@login_required
def consumer():
    return render_template('consumer.html')


@blueprint.route('/payment')
@login_required
def payment():
    return render_template('payment.html')


@blueprint.route('/products')
@login_required
def products():
    return render_template('products.html')


@blueprint.route('/review')
@login_required
def review():
    return render_template('review.html')

agroligon/routes/login_fb.py
from flask import flash
from flask_dance.consumer import oauth_authorized
from flask_dance.consumer.storage.sqla import SQLAlchemyStorage
from flask_dance.contrib.facebook import make_facebook_blueprint
from flask_login import current_user, login_user
from sqlalchemy.orm.exc import NoResultFound

from agroligon import db
from agroligon.models.oauth import OAuth
from agroligon.models.user import User

blueprint = make_facebook_blueprint(
    storage=SQLAlchemyStorage(OAuth, db.session, user=current_user),
    scope='email',
    redirect_to='home.producer'
)


@oauth_authorized.connect_via(blueprint)
def facebook_logged_in(blueprint, token):
    if not token:
        flash('Failed to log in.', category='error')
        return False

    resp = blueprint.session.get(
        '/me?fields=id,name,email,picture'
    )

    if not resp.ok:
        flash('Failed to fetch user info.')
        return False

    info = resp.json()
    fb_user_id = info['id']

    query = OAuth.query.filter_by(
        provider=blueprint.name,
        provider_user_id=fb_user_id,
    )

    try:
        oauth = query.one()
    except NoResultFound:
        oauth = OAuth(
            provider=blueprint.name,
            provider_user_id=fb_user_id,
            token=token
        )

    if oauth.user:
        login_user(oauth.user)
    else:
        user = User(
            name=info['name'],
            email=info['email'],
            picture=info['picture']['data']['url']
        )

        oauth.user = user

        db.session.add_all([user, oauth])
        db.session.commit()

        login_user(user)

    return False

agroligon/templates/index.html
{% extends 'base.html' %}

{% block title %}Καλοσωρίσατε{% endblock %}

{% block body %}
    <div class="container">
        <div class="jumbotron">

            <div class="text-center">
                <img src="{{ url_for('static', filename='images/frescopsaraki.png') }}" width="500" height="250">
                <h3 class="mt-4 mb-4">
                    Καλοσωρίσατε στο <strong class="text-primary">frescopsaraki.gr</strong>
                </h3>
                <h3 class="text-secondary">
                    Για καταναλωτές, επιχειρήσεις, επαγγελματίες και αλιείς
                </h3>
            </div>

            <hr class="mt-md-5 mb-md-5">

            <form>
                <div class="container">
                    <div class="row align-items-end">
                        <div class="col-sm-5">
                            <label for="field1"><strong>
                                <i class="fas fa-fish mr-2"></i>Τι ψάρια ψάχνετε;</strong>
                            </label>
                            <select class="form-control form-control-lg" id="field1">
                                <option>Σφυρίδα</option>
                                <option>Πεσκανδρίτσα</option>
                                <option>Συναγρίδα</option>
                                <option>Χταπόδι</option>
                                <option>...</option>
                            </select>
                        </div>
                        <div class="col-sm-4">
                            <label for="field2"><strong>
                                <i class="fas fa-home mr-2"></i>Σε ποια περιοχή;</strong>
                            </label>
                            <select class="form-control form-control-lg" id="field2">
                                <option>Παγκράτι</option>
                                <option>Κουκάκι</option>
                                <option>Βύρωνας</option>
                                <option>Καισαριανή</option>
                                <option>...</option>
                            </select>
                        </div>
                        <div class="col-sm">
                            <a href="{{ url_for('home.search') }}" class="btn btn-success btn-lg btn-block">
                                <i class="fas fa-search mr-2"></i>Αναζήτηση
                            </a>
                        </div>
                    </div>
                    <div class="row mt-3">
                        <div class="col-auto ml-auto">
                            <div class="form-check">
                                <input type="checkbox" class="form-check-input" id="exampleCheck1">
                                <label class="form-check-label" for="exampleCheck1">
                                    Να γίνει καθαρισμός ψαριών (+ 1&euro;)
                                </label>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

agroligon/templates/navbar.html
{% macro navbar(current_user) %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <a class="navbar-brand" href="{{ url_for('home.index') }}">frescopsaraki.gr</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{{ url_for('home.index') }}">Αρχική <span class="sr-only">(current)</span></a>
                </li>
                {% if current_user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('home.producer') }}">Παραγωγός</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('home.consumer') }}">Καταναλωτής</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('home.review') }}">Αξιολόγηση</a>
                    </li>
                {% endif %}

            </ul>
            {% if current_user.is_authenticated %}
                <a class="btn btn-outline-light my-2 my-sm-0" href="{{ url_for('auth.logout') }}">
                    <i class="fas fa-power-off mr-2"></i>Αποσύνδεση
                </a>
            {% else %}
                <a class="btn btn-outline-light my-2 my-sm-0" href="/login/facebook">
                    <i class="fab fa-facebook mr-2"></i>Σύνδεση με Facebook
                </a>
            {% endif %}

        </div>
    </nav>
{% endmacro %}

agroligon/templates/producer.html
{% extends 'base.html' %}

{% block title %}Επισκόπηση{% endblock %}

{% block body %}
    <div class="container">
        <div class="jumbotron pt-5 pb-5">
            <h3><i class="fas fa-ship mr-2"></i>Παραγωγός</h3>
            <hr class="mb-4">
            <li class="media">
                <img src="{{ current_user.picture }}" alt="" class="mr-3">
                <div class="media-body">
                    <h5 class="mt-0 mb-3">{{ current_user.name }}</h5>
                    <div class="d-inline-flex font-weight-bold">
                        <div class="mr-4"><i class="fas fa-star mr-1"></i>234 σκορ ποιότητας</div>
                        <div class="mr-4"><i class="fas fa-phone mr-1"></i>2103844423</div>
                        <div><i class="fas fa-city mr-1"></i>Αθήνα</div>
                    </div>
                </div>
            </li>
            <div class="alert alert-primary d-flex align-items-baseline m-0 mt-5" role="alert">
                <div>
                    <i class="fas fa-fish mr-2"></i>O Γιώργος Θεοφιλόπουλος θέλει <strong>10kg Σφυρίδα</strong> και
                    <strong>5kg Πεσκανδρίτσα</strong> στην Αθήνα.
                </div>
                <a href="#" class="btn btn-success ml-auto">
                    <i class="fas fa-check mr-2"></i>Αποδοχή παραγγελίας
                </a>
            </div>
        </div>

        <div class="jumbotron pt-5 pb-5">
            <h5><i class="fas fa-fish mr-2"></i>Τι ψάρια πιάσατε σήμερα;</h5>
            <hr class="mb-4">
            <p>Καταγράψτε τα ψάρια που πιάσατε σήμερα ώστε να εμφανίζονται στους καταναλωτές και τις επιχειρήσεις
                που θα πραγματοποιήσουν παραγγελίες.</p>
            <div class="container">
                <div class="row">
                    <div class="col-auto ml-auto">
                        <a href="{{ url_for('home.products') }}" class="btn btn-success">
                            <i class="fas fa-plus mr-2"></i>Προσθήκη Προϊόντων
                        </a>
                    </div>
                </div>
            </div>
        </div>

        <div class="jumbotron pt-5 pb-5">
            <h5><i class="fas fa-business-time mr-2"></i>Παραγγελίες</h5>
            <hr class="mb-4">

            <table class="table table-striped">
                <thead class="bg-primary text-white">
                <tr>
                    <th scope="col">Ημερομηνία</th>
                    <th scope="col">Αναλυτικά</th>
                    <th scope="col">Συνολικά Κιλά</th>
                    <th scope="col">Επιπλέον Χρεώσεις</th>
                    <th>Συνολικό Κόστος</th>
                    <th>Κατάσταση</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <th scope="row">04/06/2019</th>
                    <td>Σφυρίδα, Στήρα, Πεσκανδρίτσα</td>
                    <td>10kg</td>
                    <td>Καθάρισμα (+1&euro;)</td>
                    <td>130&euro;</td>
                    <td>
                        <a href="#" class="btn btn-primary btn-block">
                            <i class="fas fa-times mr-2"></i>Ακύρωση
                        </a>
                    </td>
                </tr>
                <tr>
                    <th scope="row">04/04/2019</th>
                    <td>Συναγρίδα, Ροφός</td>
                    <td>10kg</td>
                    <td>Καθάρισμα (+1&euro;)</td>
                    <td>130&euro;</td>
                    <td>
                        <a href="#" class="btn btn-primary btn-block disabled">
                            <i class="fas fa-check mr-2"></i>Ολοκληρώθηκε
                        </a>
                    </td>
                </tr>
                <tr>
                    <th scope="row">03/28/2019</th>
                    <td>Τσιπούρα, Συκιός, Σαργός</td>
                    <td>10kg</td>
                    <td>Καθάρισμα (+1&euro;)</td>
                    <td>130&euro;</td>
                    <td>
                        <a href="#" class="btn btn-primary btn-block disabled">
                            <i class="fas fa-check mr-2"></i>Ολοκληρώθηκε
                        </a>
                    </td>
                </tr>
                </tbody>
            </table>

        </div>

        <div class="jumbotron pt-5 pb-5">
            <h5><i class="fas fa-euro-sign mr-2"></i>Μηνιαίες Πωλήσεις</h5>
            <hr class="mb-4">
            <canvas id="line-chart" width="800" height="450"></canvas>

        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script>
        new Chart(document.getElementById("line-chart"), {
            type: 'line',
            data: {
                labels: [1500, 1600, 1700, 1750, 1800, 1850, 1900, 1950, 1999, 2050],
                datasets: [{
                    data: [86, 114, 106, 106, 107, 111, 133, 221, 783, 2478],
                    label: "Africa",
                    borderColor: "#3e95cd",
                    fill: false
                }, {
                    data: [282, 350, 411, 502, 635, 809, 947, 1402, 3700, 5267],
                    label: "Asia",
                    borderColor: "#8e5ea2",
                    fill: false
                }, {
                    data: [168, 170, 178, 190, 203, 276, 408, 547, 675, 734],
                    label: "Europe",
                    borderColor: "#3cba9f",
                    fill: false
                }, {
                    data: [40, 20, 10, 16, 24, 38, 74, 167, 508, 784],
                    label: "Latin America",
                    borderColor: "#e8c3b9",
                    fill: false
                }, {
                    data: [6, 3, 2, 2, 7, 26, 82, 172, 312, 433],
                    label: "North America",
                    borderColor: "#c45850",
                    fill: false
                }
                ]
            },
            options: {
                title: {
                    display: true,
                    text: 'World population per region (in millions)'
                }
            }
        });
    </script>
{% endblock %}

agroligon/templates/review.html
{% extends 'base.html' %}

{% block title %}Αξιολόγηση Παραγωγού{% endblock %}

{% block body %}
    <div class="container">
        <div class="jumbotron pt-5 pb-5">
            <h3><i class="fas fa-edit mr-2"></i>Αξιολόγηση Παραγωγού</h3>
            <hr class="mb-4">
            <li class="media">
                <img src="{{ current_user.picture }}" alt="" class="mr-3">
                <div class="media-body">
                    <h5 class="mt-0 mb-3">{{ current_user.name }}</h5>
                    <div class="d-inline-flex font-weight-bold">
                        <div class="mr-4"><i class="fas fa-star mr-1"></i>234 σκορ αξιοπιστίας</div>
                        <div class="mr-4"><i class="fas fa-phone mr-1"></i>2103844423</div>
                        <div><i class="fas fa-city mr-1"></i>Αθήνα</div>
                    </div>
                </div>
            </li>

            <p class="mt-4 mb-1"><strong>Φρεσκότητα</strong></p>
            <p class="text-primary">
                <i class="fas fa-star mr-2"></i>
                <i class="fas fa-star mr-2"></i>
                <i class="fas fa-star mr-2"></i>
                <i class="fas fa-star mr-2"></i>
                <i class="fas fa-star mr-2"></i>
            </p>

            <p class="mt-4 mb-1"><strong>Συνεργασία</strong></p>
            <p class="text-primary">
                <i class="fas fa-star mr-2"></i>
                <i class="fas fa-star mr-2"></i>
                <i class="fas fa-star mr-2"></i>
                <i class="fas fa-star mr-2"></i>
                <i class="far fa-star mr-2"></i>
            </p>


            <p class="mt-4 mb-1"><strong>Χρόνος Παραλαβής</strong></p>
            <p class="text-primary">
                <i class="fas fa-star mr-2"></i>
                <i class="fas fa-star mr-2"></i>
                <i class="fas fa-star mr-2"></i>
                <i class="fas fa-star mr-2"></i>
                <i class="far fa-star mr-2"></i>
            </p>

            <div class="form-group mt-4">
                <label for="text1">
                    <strong>Ποια είναι η γενική σας γνώμη για το προϊόν;</strong>
                </label>
                <textarea class="form-control" id="text1" rows="3"></textarea>
            </div>

            <div class="d-flex">
                <a href="{{ url_for('home.products') }}" class="btn btn-success ml-auto">
                    <i class="fas fa-plus mr-2"></i>Υποβολή Αξιολόγησης
                </a>
            </div>

        </div>
    </div>
{% endblock %}

agroligon/templates/search.html
{% extends 'base.html' %}

{% block title %}Αναζήτηση{% endblock %}

{% block body %}
    <div class="container">
        <div class="jumbotron">
            <div class="text-center mb-5">
                <h4>Ψάχνω <strong>Σφυρίδα</strong> και βρίσκομαι στο <strong>Παγκράτι</strong></h4>
                <h4>Θέλω <strong>3 κιλά</strong> και να είναι <strong>καθαρισμένα</strong></h4>
            </div>
            <div class="d-flex align-items-baseline">
                <h4 class="m-0">Αναζήτηση</h4>
                <p class="ml-auto m-0"><strong>3 αλιείς</strong> μπορούν να σας εξυπηρετήσουν</p>
            </div>
            <hr class="mb-5">
            <ul class="list-unstyled">
                <li class="media">
                    <img src="{{ url_for('static', filename='images/thanos.jpg') }}"
                         class="mr-3 rounded" width="100" height="80">
                    <div class="media-body">
                        <h5 class="mt-0 mb-3">Γιάννης Παπαγεωργίου</h5>
                        <div class="d-flex font-weight-bold  mb-4">
                            <div class="mr-4"><i class="fas fa-check-circle mr-1"></i>Πιστοποιημένος</div>
                            <div class="mr-4"><i class="fas fa-star mr-1"></i>192 σκορ ποιότητας</div>
                            <div class="mr-4"><i class="fas fa-phone mr-1"></i>2103844423</div>
                            <div><i class="fas fa-city mr-1"></i>Πειραιάς</div>
                        </div>
                        <p><strong>Σημερινή Ψαριά</strong></p>

                        <div class="d-flex mb-4">
                            <img src="{{ url_for('static', filename='images/fish1.jpg') }}" class="fish-image mr-3">
                            <img src="{{ url_for('static', filename='images/fish2.jpg') }}" class="fish-image mr-3">
                            <img src="{{ url_for('static', filename='images/fish3.jpg') }}" class="fish-image mr-3">
                        </div>


                        <p class="mb-0">Σφυρίδα</p>
                        <div class="progress mb-3">
                            <div class="progress-bar bg-success" role="progressbar" style="width: 42%">42%</div>
                        </div>
                        <p class="mb-0">Χταπόδι</p>
                        <div class="progress mb-3">
                            <div class="progress-bar bg-info" role="progressbar" style="width: 35%">35%</div>
                        </div>
                        <p class="mb-0">Τσιπούρα</p>
                        <div class="progress">
                            <div class="progress-bar bg-warning" role="progressbar" style="width: 23%">23%</div>
                        </div>
                        <div class="d-flex align-items-baseline">
                            <div class="mt-4">Εξυπηρέτησε <strong>38 παραγγελίες</strong> παρόμοιες με τη δική σας.
                            </div>
                            <a href="#" class="btn btn-primary ml-auto">
                                <i class="fab fa-facebook-messenger mr-2"></i>Messenger
                            </a>
                            <a href="{{ url_for('home.payment') }}" class="btn btn-success ml-2">
                                <i class="fas fa-business-time mr-2"></i>Τοποθέτηση Παραγγελίας
                            </a>
                        </div>
                    </div>
                </li>
                <hr class="mb-5 mt-5">
                <li class="media">
                    <img src="{{ url_for('static', filename='images/george.png') }}"
                         class="mr-3 rounded" width="100" height="80">
                    <div class="media-body">
                        <h5 class="mt-0 mb-3">Κώστας Αναστασόπουλος</h5>
                        <div class="d-flex font-weight-bold mb-4">
                            <div class="mr-4"><i class="fas fa-check-circle mr-1"></i>Πιστοποιημένος</div>
                            <div class="mr-4"><i class="fas fa-star mr-1"></i>112 σκορ ποιότητας</div>
                            <div class="mr-4"><i class="fas fa-phone mr-1"></i>2103825127</div>
                            <div><i class="fas fa-city mr-1"></i>Πειραιάς</div>
                        </div>
                        <p><strong>Σημερινή Ψαριά</strong></p>
                        <div class="d-flex mb-4">
                            <img src="{{ url_for('static', filename='images/fish3.jpg') }}" class="fish-image mr-3">
                            <img src="{{ url_for('static', filename='images/fish1.jpg') }}" class="fish-image mr-3">
                            <img src="{{ url_for('static', filename='images/fish2.jpg') }}" class="fish-image mr-3">
                        </div>

                        <p class="mb-0">Χταπόδι</p>
                        <div class="progress mb-3">
                            <div class="progress-bar bg-success" role="progressbar" style="width: 38%">38%</div>
                        </div>
                        <p class="mb-0">Πεσκανδρίτσα</p>
                        <div class="progress mb-3">
                            <div class="progress-bar bg-info" role="progressbar" style="width: 32%">32%</div>
                        </div>
                        <p class="mb-0">Αθερίνα</p>
                        <div class="progress">
                            <div class="progress-bar bg-warning" role="progressbar" style="width: 30%">30%</div>
                        </div>
                        <div class="d-flex align-items-baseline">
                            <div class="mt-4">Εξυπηρέτησε <strong>16 παραγγελίες</strong> παρόμοιες με τη δική σας.
                            </div>
                            <a href="#" class="btn btn-primary ml-auto">
                                <i class="fab fa-facebook-messenger mr-2"></i>Messenger
                            </a>
                            <a href="{{ url_for('home.payment') }}" class="btn btn-success ml-2">
                                <i class="fas fa-business-time mr-2"></i>Τοποθέτηση Παραγγελίας
                            </a>
                        </div>
                    </div>
                </li>
                <hr class="mb-5 mt-5">
                <li class="media">
                    <i class="fas fa-user-lock fa-3x mr-3 text-primary"></i>
                    <div class="media-body">
                        <h5 class="mt-0 mb-3">Αλιευτικός Συνεταιρισμός Μίσθωσης Λιμνοθαλλασών Μεσολογγίου</h5>
                        <div class="d-flex font-weight-bold mb-4">
                            <div class="mr-4"><i class="fas fa-check-circle mr-1"></i>Πιστοποιημένος</div>
                            <div class="mr-4"><i class="fas fa-star mr-1"></i>94 σκορ ποιότητας</div>
                            <div class="mr-4"><i class="fas fa-phone mr-1"></i>2103425129</div>
                            <div><i class="fas fa-city mr-1"></i>Μεσολόγγι</div>
                        </div>
                        <p><strong>Σημερινή Ψαριά</strong></p>
                        <div class="d-flex mb-4">
                            <img src="{{ url_for('static', filename='images/fish2.jpg') }}" class="fish-image mr-3">
                            <img src="{{ url_for('static', filename='images/fish3.jpg') }}" class="fish-image mr-3">
                            <img src="{{ url_for('static', filename='images/fish1.jpg') }}" class="fish-image mr-3">
                        </div>

                        <p class="mb-0">Τσιπούρα</p>
                        <div class="progress mb-3">
                            <div class="progress-bar bg-success" role="progressbar" style="width: 44%">44%</div>
                        </div>
                        <p class="mb-0">Λαυράκι</p>
                        <div class="progress mb-3">
                            <div class="progress-bar bg-info" role="progressbar" style="width: 35%">35%</div>
                        </div>
                        <p class="mb-0">Κέφαλος</p>
                        <div class="progress">
                            <div class="progress-bar bg-warning" role="progressbar" style="width: 21%">21%</div>
                        </div>
                        <div class="d-flex align-items-baseline">
                            <div class="mt-4">Εξυπηρέτησε <strong>12 παραγγελίες</strong> παρόμοιες με τη δική σας.
                            </div>
                            <a href="#" class="btn btn-primary ml-auto">
                                <i class="fab fa-facebook-messenger mr-2"></i>Messenger
                            </a>
                            <a href="{{ url_for('home.payment') }}" class="btn btn-success ml-2">
                                <i class="fas fa-business-time mr-2"></i>Τοποθέτηση Παραγγελίας
                            </a>
                        </div>
                    </div>
                </li>

            </ul>

            <hr class="mb-4 mt-5">
            <div class="d-flex align-items-baseline">
                <div class="mt-4 text-secondary">
                    Η παραγγελία θα σταλεί στους παραγωγούς που μπορούν να σας εξυπηρετήσουν.
                </div>
            </div>

        </div>
    </div>
{% endblock %}